In [1]:
import numpy

In [3]:
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(12,)

In [6]:
a.shape = 3,4

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a[2]

array([ 8,  9, 10, 11])

In [9]:
a[2,1]

9

In [11]:
a[:, 1]

array([1, 5, 9])

In [12]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])